name: flutter_file_manager_android
description: Android platform implementation of flutter_file_saver.
version: 2.1.0
homepage: https://github.com/TesteurManiak/flutter_file_saver
repository: https://github.com/TesteurManiak/flutter_file_saver/tree/main/packages/flutter_file_manager_android
issue_tracker: https://github.com/TesteurManiak/flutter_file_saver/issues?q=is%3Aissue+is%3Aopen+label%3Aandroid
environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_file_manager_platform_interface: ^2.0.0
  mime: ^2.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  pigeon: ^24.2.1

flutter:
  plugin:
    platforms:
      android:
        package: com.maniak.flutter_file_manager_android
        pluginClass: FlutterFileManagerAndroidPlugin
